  InstallCloudWatchAgentComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: install-cloudwatch-agent
      Platform: Windows
      Version: 1.0.0
      Description: Install and configure Amazon CloudWatch Agent
      ChangeDescription: Install CloudWatch Agent from S3 and apply basic config
      Data: |
        name: install-cloudwatch-agent
        description: Install and configure CloudWatch Agent
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: DownloadCWAgent
                action: ExecutePowerShell
                inputs:
                  commands:
                    - "[System.Net.ServicePointManager]::SecurityProtocol = 'Tls12'"
                    - "Invoke-WebRequest -Uri https://s3.amazonaws.com/amazoncloudwatch-agent/windows/amd64/latest/AmazonCloudWatchAgentInstaller.exe -OutFile C:\\AmazonCloudWatchAgentInstaller.exe"
              - name: InstallCWAgent
                action: ExecutePowerShell
                inputs:
                  commands:
                    - "Start-Process -FilePath C:\\AmazonCloudWatchAgentInstaller.exe -ArgumentList '/S' -Wait"
              - name: ConfigureCWAgent
                action: ExecutePowerShell
                inputs:
                  commands:
                    - |
                      $Config = @'
                      {
                        "agent": {
                          "metrics_collection_interval": 60,
                          "run_as_user": "Administrator"
                        },
                        "metrics": {
                          "append_dimensions": {
                            "InstanceId": "${aws:InstanceId}"
                          },
                          "metrics_collected": {
                            "LogicalDisk": {
                              "measurement": [ "% Free Space" ],
                              "metrics_collection_interval": 60,
                              "resources": [ "*" ]
                            },
                            "Memory": {
                              "measurement": [ "Available MBytes" ],
                              "metrics_collection_interval": 60
                            }
                          }
                        }
                      }
                      '@
                      $Config | Out-File -FilePath "C:\\ProgramData\\Amazon\\AmazonCloudWatchAgent\\config.json" -Encoding ascii
              - name: StartCWAgent
                action: ExecutePowerShell
                inputs:
                  commands:
                    - "C:\\Program Files\\Amazon\\AmazonCloudWatchAgent\\amazon-cloudwatch-agent-ctl.ps1 -a fetch-config -m ec2 -c file:C:\\ProgramData\\Amazon\\AmazonCloudWatchAgent\\config.json -s"