AWSTemplateFormatVersion: '2010-09-09'
Description: Golden AMI creation with SSM agent using EC2 Image Builder

Parameters:
  BaseAMI:
    Type: String
    Description: Base OS AMI ID (e.g., Amazon Linux 2)

  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet ID for the temporary build instance

  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security Group ID for build instance networking

Resources:

  ImageBuilderInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/EC2InstanceProfileForImageBuilder

  ImageBuilderInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref ImageBuilderInstanceRole

  SSMComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: InstallSSMAgent
      Platform: Linux
      Version: 1.0.0
      Data: |
        name: InstallSSMAgent
        description: Install Amazon SSM Agent
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: InstallSSM
                action: ExecuteBash
                inputs:
                  commands:
                    - yum install -y amazon-ssm-agent
                    - systemctl enable amazon-ssm-agent
                    - systemctl start amazon-ssm-agent

  GoldenImageRecipe:
    Type: AWS::ImageBuilder::ImageRecipe
    Properties:
      Name: GoldenImageWithSSM
      Version: 1.0.0
      ParentImage: !Ref BaseAMI
      Components:
        - ComponentArn: !Ref SSMComponent

  GoldenInfraConfig:
    Type: AWS::ImageBuilder::InfrastructureConfiguration
    Properties:
      Name: GoldenInfra
      InstanceProfileName: !Ref ImageBuilderInstanceProfile
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref SecurityGroupId
      TerminateInstanceOnFailure: true

  GoldenImagePipeline:
    Type: AWS::ImageBuilder::ImagePipeline
    Properties:
      Name: GoldenAMI-Pipeline
      ImageRecipeArn: !Ref GoldenImageRecipe
      InfrastructureConfigurationArn: !Ref GoldenInfraConfig
      Status: ENABLED

Outputs:
  PipelineName:
    Description: Name of the EC2 Image Builder pipeline
    Value: !Ref GoldenImagePipeline