      Components:
        - ComponentArn: !Ref InstallSSMAgentComponent
        - ComponentArn: !Ref InstallAWSCLIComponent
        - ComponentArn: !Ref InstallQualysAgentComponent
        - ComponentArn: !Ref InstallDatadogAgentComponent
        - ComponentArn: !Ref InstallMicrosoftDefenderComponent
        - ComponentArn: !Ref InstallCloudWatchAgentComponent   # <-- Add this line






[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
Invoke-WebRequest -Uri "https://amazoncloudwatch-agent.s3.amazonaws.com/windows/amd64/latest/AmazonCloudWatchAgentInstaller.exe" -OutFile "$env:TEMP\AmazonCloudWatchAgentInstaller.exe"


AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Windows Golden AMI Pipeline using EC2 Image Builder with 
  SSM Agent, AWS CLI, and Qualys Agent installation

Parameters:
  BaseAMI:
    Type: String
    Description: Base AMI ID for Windows (e.g., ami-xxxx for Windows Server 2022)

  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet ID for infrastructure configuration

  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security Group ID for the Golden Image builder instance

  AmiTags:
    Type: String
    Description: Tags to apply to the Golden Image

  TargetAccountIds:
    Type: CommaDelimitedList
    Description: List of Account IDs to share the Golden AMI with

Resources:
  ImageBuilderRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Tesco-IMS-ImageBuilder-Role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/EC2InstanceProfileForImageBuilder
        - arn:aws:iam::aws:policy/EC2InstanceProfileForImageBuilderECRContainerBuilds
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref ImageBuilderRole
      Path: "/"

  CustomSoftware:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: InstallSSMAndQualys
      Platform: Windows
      Version: 1.0.1
      Description: Install SSM Agent, AWS CLI, and Qualys Cloud Agent
      ChangeDescription: Initial setup of agents
      Data: |
        name: InstallSSMAndQualys
        description: Install SSM Agent, AWS CLI, and Qualys Cloud Agent
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: InstallSSMAgent
                action: ExecutePowerShell
                inputs:
                  commands:
                    - "[System.Net.ServicePointManager]::SecurityProtocol = 'Tls12'"
                    - "$ProgressPreference = 'SilentlyContinue'"
                    - Invoke-WebRequest -Uri "https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/windows_amd64/AmazonSSMAgentSetup.exe" -OutFile "$env:ProgramData\\AmazonSSMAgentSetup.exe"
                    - Start-Process -FilePath "$env:ProgramData\\AmazonSSMAgentSetup.exe" -ArgumentList '/S' -Wait

              - name: InstallAWSCLI
                action: ExecutePowerShell
                inputs:
                  commands:
                    - Invoke-WebRequest -Uri "https://awscli.amazonaws.com/AWSCLIV2.msi" -OutFile "$env:TEMP\\AWSCLIV2.msi"
                    - Start-Process msiexec.exe -ArgumentList '/i', "$env:TEMP\\AWSCLIV2.msi", '/quiet' -Wait

              - name: DownloadQualysAgent
                action: ExecutePowerShell
                inputs:
                  commands:
                    - "aws s3 cp s3://qualysagent050525/windows/QualysCloudAgent.exe C:\\ProgramData\\QualysCloudAgent.exe"

              - name: InstallQualysAgent
                action: ExecutePowerShell
                inputs:
                  commands:
                    - 'Start-Process -FilePath "C:\\ProgramData\\QualysCloudAgent.exe" -ArgumentList "/quiet", "CustomerId=1008b228-f7c0-76fb-80bd-41d0d653fa02", "ActivationId=ad383e19-ade4-431b-a8b2-d71bd2c1a309", "WebServiceUri=https://qagpublic.qg1.apps.qualys.co.uk/CloudAgent/" -Wait'

  ImageRecipe:
    Type: AWS::ImageBuilder::ImageRecipe
    Properties:
      Name: Tesco-IMS-GoldenImage-Windows2022-Recipe
      Description: Golden Image Recipe with Qualys and SSM Agent
      Version: 1.0.0
      ParentImage: !Ref BaseAMI
      Components:
        - ComponentArn: !Ref CustomSoftware
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            VolumeSize: 30
            VolumeType: gp3

  InfrastructureConfiguration:
    Type: AWS::ImageBuilder::InfrastructureConfiguration
    Properties:
      Name: Tesco-IMS-GoldenImage-InfrastructureConfig
      InstanceProfileName: !Ref InstanceProfile
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref SecurityGroupId
      TerminateInstanceOnFailure: true

  DistributionConfiguration:
    Type: AWS::ImageBuilder::DistributionConfiguration
    Properties:
      Name: Tesco-IMS-GoldenImage-DistributionConfig
      Description: Distribution config for Tesco Windows Golden Image
      Distributions:
        - Region: !Ref "AWS::Region"
          AmiDistributionConfiguration:
            Name: "Tesco-IMS-GoldenImage-Windows2022-{{ imagebuilder:buildDate }}"
            TargetAccountIds: !Ref TargetAccountIds
            AmiTags:
              "CreatedBy": "ImageBuilder"
              "Environment": "GoldenAMI"

  ImagePipeline:
    Type: AWS::ImageBuilder::ImagePipeline
    Properties:
      Name: Tesco-IMS-GoldenImage-Windows2022
      ImageRecipeArn: !Ref ImageRecipe
      InfrastructureConfigurationArn: !Ref InfrastructureConfiguration
      DistributionConfigurationArn: !Ref DistributionConfiguration
      Schedule:
        PipelineExecutionStartCondition: EXPRESSION_MATCH_AND_DEPENDENCY_UPDATES_AVAILABLE
        ScheduleExpression: cron(0 3 1 1,4,7,10 ? *)
      Status: ENABLED

Outputs:
  AMIPipelineName:
    Description: Name of the Image Builder pipeline
    Value: !Ref ImagePipeline