AWSTemplateFormatVersion: '2010-09-09'
Description: >
  EC2 Image Builder pipeline for Windows Server 2022 Golden AMI with
  custom softwares which includes SSM Agent, AWS CLI, datadog, cloudwatch and Qualys Agent installation

Parameters:
  BaseAMI:
    Type: String
    Description: Base AMI ID for Windows (e.g., ami-xxxx for Windows Server 2022)

  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet ID for infrastructure configuration

  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security Group ID for the Golden Image builder instance
 
  TargetAccountIds:
    Type: CommaDelimitedList
    Description: List of Account IDs to share the Golden AMI with
  
  OSCreatedDate:
    Type: String
    Description: Data at which OS image is build

  CostCenter:
    Type: String
    Description: Data at which OS image is build

  OSVersion:
    Type: String
    Description: Data at which OS is build

  Environment:
    Type: String
    Description: Data at which environment is build

  Owner:
    Type: String
    Description: Data at which owner of the resource

  Project:
    Type: String
    Description: Name of the Project

  Application:
    Type: String
    Description: Name of the Application

  Compliance:
    Type: String
    Description: Specific Compliance requirements

  Releasedate:
    Type: String
    Description: OS released date

Resources:

  ImageBuilderRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Tesco-IMS-ImageBuilder-Role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/EC2InstanceProfileForImageBuilder
        - arn:aws:iam::aws:policy/EC2InstanceProfileForImageBuilderECRContainerBuilds
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref ImageBuilderRole
      Path: "/"

  InstallSSMAgentComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: InstallSSMAgent
      Platform: Windows
      Version: 1.0.0
      Description: Install SSM Agent
      ChangeDescription: Install Amazon SSM Agent
      Data: |
        name: InstallSSMAgent
        description: Install SSM Agent
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: InstallSSMAgent
                action: ExecutePowerShell
                inputs:
                  commands:
                    - "[System.Net.ServicePointManager]::SecurityProtocol = 'Tls12'"
                    - "$ProgressPreference = 'SilentlyContinue'"
                    - Invoke-WebRequest -Uri "https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/windows_amd64/AmazonSSMAgentSetup.exe" -OutFile "$env:ProgramData\\AmazonSSMAgentSetup.exe"
                    - Start-Process -FilePath "$env:ProgramData\\AmazonSSMAgentSetup.exe" -ArgumentList '/S' -Wait

  InstallQualysAgentComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: InstallQualysAgent
      Platform: Windows
      Version: 1.0.0
      Description: Install Qualys Cloud Agent
      ChangeDescription: Install Qualys Agent from S3
      Data: |
        name: InstallQualysAgent
        description: Install Qualys Cloud Agent
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: InstallQualysAgent
                action: ExecutePowerShell
                inputs:
                  commands:
                    - "[System.Net.ServicePointManager]::SecurityProtocol = 'Tls12'"
                    - "$ProgressPreference = 'SilentlyContinue'"
                    - aws s3 cp s3://ims-prod-s3-euw1-gibinaries/windows/QualysCloudAgent.exe "C:\\"
                    - 'C:\\QualysCloudAgent.exe CustomerId="{1008b228-f7c0-76fb-80bd-41d0d653fa02}" ActivationId="{ad383e19-ade4-431b-a8b2-d71bd2c1a309}" WebServiceUri=https://qagpublic.qg1.apps.qualys.co.uk/CloudAgent/'
  
  InstallDatadogAgentComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: install-datadog-agent
      Platform: Windows
      Version: 1.0.0
      Description: Install Datadog Agent
      ChangeDescription: Install Datadog Agent using MSI
      Data: |
        name: install-datadog-agent
        description: Install Datadog Agent
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: InstallDatadog
                action: ExecutePowerShell
                inputs:
                  commands:
                    - Start-Process -Wait -PassThru msiexec -ArgumentList '/qn /i "https://windows-agent.datadoghq.com/datadog-agent-7-latest.amd64.msi" /log C:\Windows\SystemTemp\install-datadog.log APIKEY="924b0950633350ed6c4f4bf995b3a90d" SITE="datadoghq.eu"'
  ImageRecipe:
    Type: AWS::ImageBuilder::ImageRecipe
    Properties:
      Name: Tesco-IMS-GoldenImage-Windows2022-Recipe
      Version: 1.0.0
      ParentImage: !Ref BaseAMI
      Description: Windows Server 2022 Golden AMI with SSM, CLI, and Qualys
      Components:
        - ComponentArn: !Ref InstallSSMAgentComponent
        - ComponentArn: arn:aws:imagebuilder:eu-west-1:aws:component/aws-cli-version-2-windows/1.0.0/1
        - ComponentArn: !Ref InstallQualysAgentComponent
        - ComponentArn: !Ref InstallDatadogAgentComponent
        - ComponentArn: arn:aws:imagebuilder:eu-west-1:aws:component/amazon-cloudwatch-agent-windows/1.0.0/1
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            VolumeSize: 128
            VolumeType: gp3

  InfrastructureConfiguration:
    Type: AWS::ImageBuilder::InfrastructureConfiguration
    Properties:
      Name: Tesco-IMS-GoldenImage-InfrastructureConfig
      InstanceProfileName: !Ref InstanceProfile
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref SecurityGroupId
      TerminateInstanceOnFailure: true

  DistributionConfiguration:
    Type: AWS::ImageBuilder::DistributionConfiguration
    Properties:
      Name: Tesco-IMS-GoldenImage-DistributionConfig
      Description: Distribution config for Tesco Windows Golden Image
      Distributions:
        - Region: !Ref "AWS::Region"
          AmiDistributionConfiguration:
            Name: "Tesco-IMS-GoldenImage-Windows2022-{{ imagebuilder:buildDate }}"
            TargetAccountIds: !Ref TargetAccountIds

  ImagePipeline:
    Type: AWS::ImageBuilder::ImagePipeline
    Properties:
      Name: Tesco-IMS-GoldenImage-Windows2022
      ImageRecipeArn: !Ref ImageRecipe
      InfrastructureConfigurationArn: !Ref InfrastructureConfiguration
      DistributionConfigurationArn: !Ref DistributionConfiguration
      Schedule:
        PipelineExecutionStartCondition: EXPRESSION_MATCH_AND_DEPENDENCY_UPDATES_AVAILABLE
        ScheduleExpression: cron(0 9 ? * 2#3 *)
      Status: ENABLED
      Tags:
        OSCreatedDate: !Ref OSCreatedDate
        OSVersion: !Ref OSVersion
        Environment: !Ref Environment
        Owner: !Ref Owner
        Project: !Ref Project
        Application: !Ref Application
        Releasedate: !Ref Releasedate
        CostCenter: !Ref CostCenter

Outputs:
  PipelineName:
    Description: Name of the EC2 Image Builder pipeline
    Value: !Ref ImagePipeline
