AWSTemplateFormatVersion: '2010-09-09'
Description: DevOps Setup - Jenkins, SonarQube, Nexus on EC2 (non-hardcoded)

Parameters:
  VpcCIDR:
    Type: String
    Default: 10.50.0.0/16
  SubnetCIDR:
    Type: String
    Default: 10.50.1.0/24
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 Key Pair for SSH access
  InstanceType:
    Type: String
    Default: t3.medium
    AllowedValues:
      - t2.medium
      - t3.medium
      - t3.large
  AZIndex:
    Type: Number
    Default: 0
    Description: Index to select AZ from available list (0 = first AZ)

Resources:

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: DevOps-VPC

  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref SubnetCIDR
      AvailabilityZone: !Select [!Ref AZIndex, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: DevOps-Subnet

  IGW:
    Type: AWS::EC2::InternetGateway

  AttachIGW:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref IGW

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  Route:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IGW

  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Subnet
      RouteTableId: !Ref RouteTable

  DevOpsSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Allow Jenkins (8080), SonarQube (9000), Nexus (8081), SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9000
          ToPort: 9000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8081
          ToPort: 8081
          CidrIp: 0.0.0.0/0

  # Dynamic AMI for Amazon Linux 2023 via SSM
  AL2023Image:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64

  JenkinsInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: !Ref AL2023Image
      SubnetId: !Ref Subnet
      SecurityGroupIds: [!Ref DevOpsSG]
      Tags:
        - Key: Name
          Value: Jenkins
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          amazon-linux-extras enable java-openjdk11
          yum install -y java-11-openjdk
          wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
          rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
          yum install -y jenkins
          systemctl enable jenkins
          systemctl start jenkins

  SonarQubeInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: !Ref AL2023Image
      SubnetId: !Ref Subnet
      SecurityGroupIds: [!Ref DevOpsSG]
      Tags:
        - Key: Name
          Value: SonarQube
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          amazon-linux-extras enable java-openjdk11
          yum install -y java-11-openjdk unzip wget
          cd /opt
          wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-10.4.1.88267.zip
          unzip sonarqube-10.4.1.88267.zip
          mv sonarqube-* sonarqube
          useradd sonar
          chown -R sonar:sonar /opt/sonarqube
          su - sonar -c "/opt/sonarqube/bin/linux-x86-64/sonar.sh start"

  NexusInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: !Ref AL2023Image
      SubnetId: !Ref Subnet
      SecurityGroupIds: [!Ref DevOpsSG]
      Tags:
        - Key: Name
          Value: Nexus
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y java-11-openjdk wget
          cd /opt
          wget https://download.sonatype.com/nexus/3/latest-unix.tar.gz
          tar -xvzf latest-unix.tar.gz
          mv nexus-* nexus
          useradd nexus
          chown -R nexus:nexus /opt/nexus
          chown -R nexus:nexus /opt/sonatype-work
          echo 'run_as_user="nexus"' > /opt/nexus/bin/nexus.rc
          su - nexus -c "/opt/nexus/bin/nexus start"

Outputs:
  JenkinsIP:
    Value: !GetAtt JenkinsInstance.PublicIp
  SonarQubeIP:
    Value: !GetAtt SonarQubeInstance.PublicIp
  NexusIP:
    Value: !GetAtt NexusInstance.PublicIp