AWSTemplateFormatVersion: '2010-09-09'
Description: Windows Golden AMI Pipeline using EC2 Image Builder with PowerShell Component and SSM Agent installation.

Parameters:
  BaseAMI:
    Type: String
    Description: Base AMI ID for Windows (e.g., ami-xxxx for Windows Server 2019)

  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet ID for infrastructure configuration

  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security Group ID for the build instance

  #KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 KeyPair name for accessing the instance

Resources:
  ImageBuilderRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: IMS-imagebuider-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/EC2InstanceProfileForImageBuilder
        - arn:aws:iam::aws:policy/EC2InstanceProfileForImageBuilderECRContainerBuilds

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref ImageBuilderRole
      Path: "/"

  Customsoftware:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: InstallCustomsoftware
      Platform: Windows
      Version: 1.0.0
      Description: Installs SSM Agent
      ChangeDescription: Initial version
      Data: |
        name: InstallPowerShellAndTools
        description: Install PowerShell 7, RSAT, and SSM Agent
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: InstallPowerShell
                action: ExecutePowerShell
                inputs:
                  commands:
                    - Invoke-WebRequest -Uri "https://github.com/PowerShell/PowerShell/releases/download/v7.4.0/PowerShell-7.4.0-win-x64.msi" -OutFile "C:\\powershell.msi"
                    - Start-Process msiexec.exe -ArgumentList '/i C:\\powershell.msi /quiet' -Wait
                    - Install-WindowsFeature -Name RSAT-AD-PowerShell
              - name: InstallSSMAgent
                action: ExecutePowerShell
                inputs:
                  commands:
                    - "[System.Net.ServicePointManager]::SecurityProtocol = 'Tls12'"
                    - "$progressPreference = 'silentlyContinue'"
                    - Invoke-WebRequest -Uri "https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/windows_amd64/AmazonSSMAgentSetup.exe" -OutFile "$env:USERPROFILE\\Desktop\\SSMAgent_latest.exe"
                    - Start-Process -FilePath "$env:USERPROFILE\\Desktop\\SSMAgent_latest.exe" -ArgumentList "/S" -Wait

  ImageRecipe:
    Type: AWS::ImageBuilder::ImageRecipe
    Properties:
      Name: IMS-golden-imagerecipe
      Version: 1.0.0
      ParentImage: !Ref BaseAMI
      Components:
        - ComponentArn: !Ref PowerShellComponent
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            VolumeSize: 30
            VolumeType: gp3

  InfrastructureConfiguration:
    Type: AWS::ImageBuilder::InfrastructureConfiguration
    Properties:
      Name: ssm-infra
      InstanceProfileName: !Ref InstanceProfile
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref SecurityGroupId
      TerminateInstanceOnFailure: true
      KeyPair: !Ref KeyName

  ImagePipeline:
    Type: AWS::ImageBuilder::ImagePipeline
    Properties:
      Name: Tesco-IMS-GoldenImage-Windows2022
      ImageRecipeArn: !Ref ImageRecipe
      InfrastructureConfigurationArn: !Ref InfrastructureConfiguration
      Schedule:
        PipelineExecutionStartCondition: EXPRESSION_MATCH_AND_DEPENDENCY_UPDATES_AVAILABLE
        ScheduleExpression: cron(0 3 1 1,4,7,10 ? *)
      Status: ENABLED

Outputs:
  AMIPipelineName:
    Description: Name of the Golden AMI Pipeline
    Value: !Ref ImagePipeline
