AWSTemplateFormatVersion: "2010-09-09"
Description: >
  DevOps Environment Template - VPC with 3 Private Subnets and EC2 Instances for Jenkins, SonarQube, and Nexus

Parameters:
  VpcCIDR:
    Type: String
    Default: "10.0.0.0/21"
    Description: CIDR block for the VPC
    AllowedPattern: '^10\.(?:[0-9]{1,3}\.){2}[0-9]{1,3}/(2[1-8])$'
    ConstraintDescription: Must be a valid CIDR block from /21 to /28 in 10.x.x.x format

  PrivateSubnet1CIDR:
    Type: String
    Default: "10.0.1.0/24"
    Description: CIDR block for Jenkins subnet
    AllowedPattern: '^10\.(?:[0-9]{1,3}\.){2}[0-9]{1,3}/(2[3-8])$'
    ConstraintDescription: Must be a valid CIDR block from /23 to /28 in 10.x.x.x format

  PrivateSubnet2CIDR:
    Type: String
    Default: "10.0.2.0/24"
    Description: CIDR block for SonarQube subnet
    AllowedPattern: '^10\.(?:[0-9]{1,3}\.){2}[0-9]{1,3}/(2[3-8])$'
    ConstraintDescription: Must be a valid CIDR block from /23 to /28 in 10.x.x.x format

  PrivateSubnet3CIDR:
    Type: String
    Default: "10.0.3.0/24"
    Description: CIDR block for Nexus subnet
    AllowedPattern: '^10\.(?:[0-9]{1,3}\.){2}[0-9]{1,3}/(2[3-8])$'
    ConstraintDescription: Must be a valid CIDR block from /23 to /28 in 10.x.x.x format

  InstanceType:
    Type: String
    Default: "t3.medium"
    Description: EC2 instance type for all instances

  ImageId:
    Type: AWS::EC2::Image::Id
    Description: AMI ID for launching EC2 instances

Resources:

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: DevOps-VPC

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnet1CIDR
      AvailabilityZone: !Select [0, !GetAZs ""]
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: DevOps-PrivateSubnet-Jenkins

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnet2CIDR
      AvailabilityZone: !Select [1, !GetAZs ""]
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: DevOps-PrivateSubnet-SonarQube

  PrivateSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnet3CIDR
      AvailabilityZone: !Select [2, !GetAZs ""]
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: DevOps-PrivateSubnet-Nexus

  DevOpsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow all traffic within VPC
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: !Ref VpcCIDR
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: "0.0.0.0/0"
      Tags:
        - Key: Name
          Value: DevOps-Internal-SG

  JenkinsInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      SubnetId: !Ref PrivateSubnet1
      ImageId: !Ref ImageId
      SecurityGroupIds:
        - !Ref DevOpsSecurityGroup
      Tags:
        - Key: Name
          Value: Jenkins-EC2

  SonarQubeInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      SubnetId: !Ref PrivateSubnet2
      ImageId: !Ref ImageId
      SecurityGroupIds:
        - !Ref DevOpsSecurityGroup
      Tags:
        - Key: Name
          Value: SonarQube-EC2

  NexusInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      SubnetId: !Ref PrivateSubnet3
      ImageId: !Ref ImageId
      SecurityGroupIds:
        - !Ref DevOpsSecurityGroup
      Tags:
        - Key: Name
          Value: Nexus-EC2

Outputs:
  VpcId:
    Description: VPC ID
    Value: !Ref VPC

  JenkinsInstanceId:
    Description: Jenkins EC2 Instance ID
    Value: !Ref JenkinsInstance

  SonarQubeInstanceId:
    Description: SonarQube EC2 Instance ID
    Value: !Ref SonarQubeInstance

  NexusInstanceId:
    Description: Nexus EC2 Instance ID
    Value: !Ref NexusInstance