AWSTemplateFormatVersion: '2010-09-09'
Description: >
  EC2 Image Builder pipeline for Windows Golden AMI with SSM Agent, AWS CLI, Qualys Agent, Datadog Agent, and Microsoft Defender

Parameters:
  BaseAMI:
    Type: String
    Description: Base AMI ID for Windows (e.g., ami-xxxx for Windows Server 2022)

  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet ID for infrastructure configuration

  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security Group ID for the Golden Image builder instance

  AmiTags:
    Type: String
    Description: Tags to apply to the Golden Image

  TargetAccountIds:
    Type: CommaDelimitedList
    Description: List of Account IDs to share the Golden AMI with

Resources:

  ImageBuilderRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Tesco-IMS-ImageBuilder-Role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/EC2InstanceProfileForImageBuilder
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref ImageBuilderRole

  InstallSSMAgentComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: install-ssm-agent
      Platform: Windows
      Version: 1.0.0
      Description: Install Amazon SSM Agent
      ChangeDescription: Install Amazon SSM Agent
      Data: |
        name: install-ssm-agent
        description: Install SSM Agent
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: InstallSSMAgent
                action: ExecutePowerShell
                inputs:
                  commands:
                    - "[System.Net.ServicePointManager]::SecurityProtocol = 'Tls12'"
                    - "Invoke-WebRequest -Uri 'https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/windows_amd64/AmazonSSMAgentSetup.exe' -OutFile '$env:ProgramData\\AmazonSSMAgentSetup.exe'"
                    - "Start-Process -FilePath '$env:ProgramData\\AmazonSSMAgentSetup.exe' -ArgumentList '/S' -Wait"

  InstallAWSCLIComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: install-aws-cli
      Platform: Windows
      Version: 1.0.0
      Description: Install AWS CLI
      ChangeDescription: Install AWS CLI
      Data: |
        name: install-aws-cli
        description: Install AWS CLI
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: InstallAWSCLI
                action: ExecutePowerShell
                inputs:
                  commands:
                    - "Invoke-WebRequest -Uri 'https://awscli.amazonaws.com/AWSCLIV2.msi' -OutFile '$env:TEMP\\AWSCLIV2.msi'"
                    - "Start-Process msiexec.exe -ArgumentList '/i', '$env:TEMP\\AWSCLIV2.msi', '/quiet' -Wait"

  InstallQualysAgentComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: install-qualys-agent
      Platform: Windows
      Version: 1.0.0
      Description: Install Qualys Agent
      ChangeDescription: Install Qualys Agent from S3
      Data: |
        name: install-qualys-agent
        description: Install Qualys Cloud Agent
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: InstallQualys
                action: ExecutePowerShell
                inputs:
                  commands:
                    - "[System.Net.ServicePointManager]::SecurityProtocol = 'Tls12'"
                    - "aws s3 cp s3://qualysagent050525/windows/QualysCloudAgent.exe C:\\"
                    - "C:\\QualysCloudAgent.exe CustomerId=1008b228-f7c0-76fb-80bd-41d0d653fa02 ActivationId=ad383e19-ade4-431b-a8b2-d71bd2c1a309 WebServiceUri=https://qagpublic.qg1.apps.qualys.co.uk/CloudAgent/"

  InstallDatadogAgentComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: install-datadog-agent
      Platform: Windows
      Version: 1.0.0
      Description: Install Datadog Agent
      ChangeDescription: Install Datadog Agent using MSI
      Data: |
        name: install-datadog-agent
        description: Install Datadog Agent
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: InstallDatadog
                action: ExecutePowerShell
                inputs:
                  commands:
                    - "[System.Net.ServicePointManager]::SecurityProtocol = 'Tls12'"
                    - "Invoke-WebRequest -Uri 'https://s3.amazonaws.com/ddagent-windows-stable/datadog-agent-7-latest.amd64.msi' -OutFile 'C:\\datadog-agent.msi'"
                    - "Start-Process msiexec.exe -ArgumentList '/i', 'C:\\datadog-agent.msi', '/qn', 'APIKEY=100120806b7b4de36828e7da575cdf40', 'SITE=datadoghq.com' -Wait"

  InstallMicrosoftDefenderComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: install-microsoft-defender
      Platform: Windows
      Version: 1.0.0
      Description: Enable Microsoft Defender Antivirus
      ChangeDescription: Enable Microsoft Defender and ensure real-time protection
      Data: |
        name: install-microsoft-defender
        description: Enable Microsoft Defender
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: EnableDefender
                action: ExecutePowerShell
                inputs:
                  commands:
                    - "Set-MpPreference -DisableRealtimeMonitoring $false"
                    - "Set-MpPreference -MAPSReporting Advanced"
                    - "Set-MpPreference -SubmitSamplesConsent SendSafeSamples"
                    - "Start-Service WinDefend"
                    - "Set-Service -Name WinDefend -StartupType Automatic"

  ImageRecipe:
    Type: AWS::ImageBuilder::ImageRecipe
    Properties:
      Name: Tesco-IMS-GoldenImage-Windows2022-Recipe-v2
      Version: 1.0.1
      ParentImage: !Ref BaseAMI
      Description: Windows Server 2022 Golden AMI with SSM, CLI, Qualys, Datadog, and Defender
      Components:
        - ComponentArn: !Ref InstallSSMAgentComponent
        - ComponentArn: !Ref InstallAWSCLIComponent
        - ComponentArn: !Ref InstallQualysAgentComponent
        - ComponentArn: !Ref InstallDatadogAgentComponent
        - ComponentArn: !Ref InstallMicrosoftDefenderComponent
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            VolumeSize: 40
            VolumeType: gp3

  InfrastructureConfiguration:
    Type: AWS::ImageBuilder::InfrastructureConfiguration
    Properties:
      Name: Tesco-IMS-GoldenImage-InfrastructureConfig
      InstanceProfileName: !Ref InstanceProfile
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref SecurityGroupId
      TerminateInstanceOnFailure: true

  DistributionConfiguration:
    Type: AWS::ImageBuilder::DistributionConfiguration
    Properties:
      Name: Tesco-IMS-GoldenImage-DistributionConfig
      Description: Distribution config for Tesco Windows Golden Image
      Distributions:
        - Region: !Ref "AWS::Region"
          AmiDistributionConfiguration:
            Name: "Tesco-IMS-GoldenImage-Windows2022-{{ imagebuilder:buildDate }}"
            TargetAccountIds: !Ref TargetAccountIds
            AmiTags:
              CreatedBy: ImageBuilder
              Environment: GoldenAMI

  ImagePipeline:
    Type: AWS::ImageBuilder::ImagePipeline
    Properties:
      Name: Tesco-IMS-GoldenImage-Windows2022-Pipeline
      ImageRecipeArn: !Ref ImageRecipe
      InfrastructureConfigurationArn: !Ref InfrastructureConfiguration
      DistributionConfigurationArn: !Ref DistributionConfiguration
      Status: ENABLED