AWSTemplateFormatVersion: '2010-09-09'
Description: Windows Golden AMI Pipeline using EC2 Image Builder with SSM and Qualys Agent Installation

Parameters:
  BaseAMI:
    Type: String
    Description: Base AMI ID for Windows (e.g., ami-xxxx for Windows Server 2022)
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet ID for infrastructure configuration
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID for the security group
  AmiTags:
    Type: String
    Description: Tags to apply to the Golden Image
  TargetAccountIds:
    Type: CommaDelimitedList
    Description: List of Account IDs with whom Golden/Base image will be shared

Resources:
  ImageBuilderRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Tesco-IMS-ImageBuilder-Role-1-test-Qualys
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/EC2InstanceProfileForImageBuilder
        - arn:aws:iam::aws:policy/EC2InstanceProfileForImageBuilderECRContainerBuilds
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref ImageBuilderRole
      Path: "/"

  ImageBuilderSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Image Builder instances
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 0
          CidrIp: 0.0.0.0/0

  Customsoftware:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: InstallSSMAndQualys
      Platform: Windows
      Version: 1.0.0
      Description: Install SSM Agent and Qualys Cloud Agent
      ChangeDescription: Added SSM and Qualys agent installations
      Data: |
        name: InstallSSMAndQualys
        description: Install SSM Agent and Qualys Cloud Agent
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: InstallSSMAgent
                action: ExecutePowerShell
                inputs:
                  commands:
                    - "[System.Net.ServicePointManager]::SecurityProtocol = 'Tls12'"
                    - "$progressPreference = 'silentlyContinue'"
                    - Invoke-WebRequest -Uri "https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/windows_amd64/AmazonSSMAgentSetup.exe" -OutFile "$env:ProgramData\\AmazonSSMAgentSetup.exe"
                    - Start-Process -FilePath "$env:ProgramData\\AmazonSSMAgentSetup.exe" -ArgumentList '/S' -Wait
              - name: InstallQualysAgent
                action: ExecutePowerShell
                inputs:
                  commands:
                    - "[System.Net.ServicePointManager]::SecurityProtocol = 'Tls12'"
                    - "$progressPreference = 'silentlyContinue'"
                    - Invoke-WebRequest -Uri "https://your-s3-bucket-name.s3.eu-west-1.amazonaws.com/windows/QualysCloudAgent.msi" -OutFile "$env:ProgramData\\QualysCloudAgent.msi"
                    - Start-Process msiexec.exe -ArgumentList '/i', "$env:ProgramData\\QualysCloudAgent.msi", 'ActivationId=902ab11f-5dba-4233-ace3-fd1763289ed2', 'CustomerId=bf0defd6-1e4a-da0d-8289-27ca9236ee31', 'ServerUri=https://qagpublic.qg1.apps.qualys.in/CloudAgent/', '/quiet' -Wait

  ImageRecipe:
    Type: AWS::ImageBuilder::ImageRecipe
    Properties:
      Name: Tesco-IMS-GoldenImage-Windows2022-Recipe
      Description: Tesco-IMS-GoldenImage-Windows2022-Recipe
      Version: 1.0.0
      ParentImage: !Ref BaseAMI
      Components:
        - ComponentArn: !Ref Customsoftware
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            VolumeSize: 30
            VolumeType: gp3

  InfrastructureConfiguration:
    Type: AWS::ImageBuilder::InfrastructureConfiguration
    Properties:
      Name: Tesco-IMS-GoldenImage-InfrastructureConfig
      Description: Tesco-IMS-GoldenImage-InfrastructureConfig
      InstanceProfileName: !Ref InstanceProfile
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref ImageBuilderSecurityGroup
      TerminateInstanceOnFailure: true

  DistributionConfiguration:
    Type: AWS::ImageBuilder::DistributionConfiguration
    Properties:
      Name: Tesco-IMS-GoldenImage-DistributionConfig
      Description: Distribution config for Tesco Windows Golden Image
      Distributions:
        - Region: !Ref "AWS::Region"
          AmiDistributionConfiguration:
            Name: "Tesco-IMS-GoldenImage-Windows2022-{{ imagebuilder:buildDate }}"
            TargetAccountIds: !Ref TargetAccountIds
            AmiTags:
              CreatedBy: "ImageBuilder"
              Environment: "GoldenAMI"

  ImagePipeline:
    Type: AWS::ImageBuilder::ImagePipeline
    Properties:
      Name: Tesco-IMS-GoldenImage-Windows2022
      Description: Tesco-IMS-GoldenImage-Windows2022
      ImageRecipeArn: !Ref ImageRecipe
      InfrastructureConfigurationArn: !Ref InfrastructureConfiguration
      DistributionConfigurationArn: !Ref DistributionConfiguration
      Schedule:
        PipelineExecutionStartCondition: EXPRESSION_MATCH_AND_DEPENDENCY_UPDATES_AVAILABLE
        ScheduleExpression: cron(0 3 1 1,4,7,10 ? *)
      Status: ENABLED

Outputs:
  AMIPipelineName:
    Description: Name of the Golden AMI Pipeline
    Value: !Ref ImagePipeline