AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation template to set up Security Account Infrastructure including
  Inspection VPC, Subnets, Route Tables, AWS Network Firewall, CloudWAN Attachment,
  and placeholders for Entra ID integration and AWS security services.

Parameters:
  VpcCidr:
    Type: String
    Default: 10.10.0.0/16
    Description: CIDR block for the Inspection VPC

  ZscalerSubnet1Cidr:
    Type: String
    Default: 10.10.1.0/24
    Description: CIDR block for Zscaler Subnet 1

  ZscalerSubnet2Cidr:
    Type: String
    Default: 10.10.2.0/24
    Description: CIDR block for Zscaler Subnet 2

  AvailabilityZone1:
    Type: AWS::EC2::AvailabilityZone::Name
    Description: First Availability Zone

  AvailabilityZone2:
    Type: AWS::EC2::AvailabilityZone::Name
    Description: Second Availability Zone

  FirewallPolicyArn:
    Type: String
    Description: ARN of the AWS Network Firewall Policy

  CoreNetworkId:
    Type: String
    Description: ID of the AWS CloudWAN Core Network

  NatGatewayId:
    Type: String
    Description: ID of the NAT Gateway in the Network Account

Resources:
  InspectionVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: Security-Inspection-VPC

  ZscalerSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref InspectionVPC
      CidrBlock: !Ref ZscalerSubnet1Cidr
      AvailabilityZone: !Ref AvailabilityZone1
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: Zscaler-ZIA-Prod-Subnet1

  ZscalerSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref InspectionVPC
      CidrBlock: !Ref ZscalerSubnet2Cidr
      AvailabilityZone: !Ref AvailabilityZone2
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: Zscaler-ZIA-Prod-Subnet2

  SecurityRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref InspectionVPC
      Tags:
        - Key: Name
          Value: Security-RouteTable

  ZscalerSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref ZscalerSubnet1
      RouteTableId: !Ref SecurityRouteTable

  ZscalerSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref ZscalerSubnet2
      RouteTableId: !Ref SecurityRouteTable

  DefaultRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref SecurityRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGatewayId

  CloudWANAttachment:
    Type: AWS::NetworkManager::VpcAttachment
    Properties:
      CoreNetworkId: !Ref CoreNetworkId
      SubnetArns:
        - !Sub arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:subnet/${ZscalerSubnet1}
        - !Sub arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:subnet/${ZscalerSubnet2}
      VpcArn: !Sub arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:vpc/${InspectionVPC}
      Tags:
        - Key: Name
          Value: Security-VPC-Attachment

  NetworkFirewall:
    Type: AWS::NetworkFirewall::Firewall
    Properties:
      FirewallName: Security-NetworkFirewall
      FirewallPolicyArn: !Ref FirewallPolicyArn
      VpcId: !Ref InspectionVPC
      SubnetMappings:
        - SubnetId: !Ref ZscalerSubnet1
        - SubnetId: !Ref ZscalerSubnet2
      DeleteProtection: false
      SubnetChangeProtection: false
      FirewallPolicyChangeProtection: false
      Tags:
        - Key: Name
          Value: Security-NetworkFirewall

  # Placeholders for Entra ID Integration and AWS Security Services
  # These resources require additional configuration and are represented as placeholders.

  # EntraIDIntegration:
  #   Type: Custom::EntraIDIntegration
  #   Properties:
  #     ServiceToken: <Lambda ARN or other integration mechanism>
  #     Configuration: <Integration details>

  # SecurityHub:
  #   Type: AWS::SecurityHub::Hub
  #   Properties:
  #     Tags:
  #       - Key: Name
  #         Value: SecurityHub

  # GuardDuty:
  #   Type: AWS::GuardDuty::Detector
  #   Properties:
  #     Enable: true
  #     Tags:
  #       - Key: Name
  #         Value: GuardDuty

  # FirewallManager:
  #   Type: AWS::FMS::Policy
  #   Properties:
  #     PolicyName: SecurityPolicy
  #     # Additional properties...

  # WAF:
  #   Type: AWS::WAFv2::WebACL
  #   Properties:
  #     Name: SecurityWebACL
  #     Scope: REGIONAL
  #     DefaultAction:
  #       Allow: {}
  #     VisibilityConfig:
  #       SampledRequestsEnabled: true
  #       CloudWatchMetricsEnabled: true
  #       MetricName: SecurityWebACL

  # Shield:
  #   Type: AWS::Shield::Protection
  #   Properties:
  #     Name: SecurityShieldProtection
  #     ResourceArn: <Resource ARN to protect>

Outputs:
  VpcId:
    Description: ID of the Inspection VPC
    Value: !Ref InspectionVPC

  ZscalerSubnet1Id:
    Description: ID of Zscaler Subnet 1
    Value: !Ref ZscalerSubnet1

  ZscalerSubnet2Id:
    Description: ID of Zscaler Subnet 2
    Value: !Ref ZscalerSubnet2

  SecurityRouteTableId:
    Description: ID of the Security Route Table
    Value: !Ref SecurityRouteTable

  NetworkFirewallId:
    Description: ID of the AWS Network Firewall
    Value: !Ref NetworkFirewall

  CloudWANAttachmentId:
    Description: ID of the CloudWAN Attachment
    Value: !Ref CloudWANAttachment