AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation template to create 1 VPC, 2 private subnets, 1 security group,
  and 3 EC2 instances with validated CIDR inputs and no default values.

Parameters:
  VpcCIDR:
    Type: String
    Description: CIDR block for the VPC
    AllowedPattern: '^10\\.(?:[0-9]{1,3}\\.){2}[0-9]{1,3}/(2[1-8])$'
    ConstraintDescription: Must be a valid CIDR block from /21 to /28 in 10.x.x.x/ format.

  PrivateSubnet1CIDR:
    Type: String
    Description: CIDR block for Private Subnet 1
    AllowedPattern: '^10\\.(?:[0-9]{1,3}\\.){2}[0-9]{1,3}/(2[3-8])$'
    ConstraintDescription: Must be a valid CIDR block from /23 to /28 in 10.x.x.x/ format.

  PrivateSubnet2CIDR:
    Type: String
    Description: CIDR block for Private Subnet 2
    AllowedPattern: '^10\\.(?:[0-9]{1,3}\\.){2}[0-9]{1,3}/(2[3-8])$'
    ConstraintDescription: Must be a valid CIDR block from /23 to /28 in 10.x.x.x/ format.

  ImageId:
    Type: AWS::EC2::Image::Id
    Description: AMI ID for launching the EC2 instances

  InstanceType:
    Type: String
    Description: EC2 instance type for all instances
    AllowedValues:
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - t3.xlarge
      - t3.2xlarge
    ConstraintDescription: Must be a valid EC2 instance type.

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: VPC

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnet1CIDR
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: PrivateSubnet-1

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnet2CIDR
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: PrivateSubnet-2

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: SG

  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      SubnetId: !Ref PrivateSubnet1
      ImageId: !Ref ImageId
      SecurityGroupIds:
        - !Ref SecurityGroup
      Tags:
        - Key: Name
          Value: EC2-Instance-1

  EC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      SubnetId: !Ref PrivateSubnet2
      ImageId: !Ref ImageId
      SecurityGroupIds:
        - !Ref SecurityGroup
      Tags:
        - Key: Name
          Value: EC2-Instance-2

  EC2Instance3:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      SubnetId: !Ref PrivateSubnet1
      ImageId: !Ref ImageId
      SecurityGroupIds:
        - !Ref SecurityGroup
      Tags:
        - Key: Name
          Value: EC2-Instance-3

Outputs:
  VPCId:
    Description: ID of the VPC
    Value: !Ref VPC

  PrivateSubnet1Id:
    Description: ID of Private Subnet 1
    Value: !Ref PrivateSubnet1

  PrivateSubnet2Id:
    Description: ID of Private Subnet 2
    Value: !Ref PrivateSubnet2

  SecurityGroupId:
    Description: ID of Security Group
    Value: !Ref SecurityGroup

  EC2Instance1Id:
    Description: ID of EC2 Instance 1
    Value: !Ref EC2Instance1

  EC2Instance2Id:
    Description: ID of EC2 Instance 2
    Value: !Ref EC2Instance2
